/*
    Clase para crear un perfil.
    Posteriormetne será una clase para editar los datos básicos 
    de un perfil de usuario
 */
package emisora.vista;


import emisora.Entidades.TipoDocumentoEn;
import emisora.Entidades.UsuarioEn;
import emisora.Negocio.UsuarioNg;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Dacamoty
 */
public class RegistroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Editar
     */
    public RegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNombre3 = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblDocumento = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblNacimiento = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jdcCalendar = new com.toedter.calendar.JDateChooser();
        cbxTipoDocu = new javax.swing.JComboBox<>();
        txtNombre2 = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        txtPassConfirm = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        lblBotonCerrar = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar datos de Usuario");

        jPanel1.setBackground(new java.awt.Color(55, 55, 55));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emisora/image/editarusuario.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Editar usuario");

        lblNombre3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre3.setForeground(new java.awt.Color(153, 153, 153));
        lblNombre3.setText("Nombre");

        lblApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(153, 153, 153));
        lblApellido.setText("Apellido");

        lblDocumento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDocumento.setForeground(new java.awt.Color(153, 153, 153));
        lblDocumento.setText("Documento");

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPass.setForeground(new java.awt.Color(153, 153, 153));
        lblPass.setText("Contraseña");

        lblNacimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNacimiento.setForeground(new java.awt.Color(153, 153, 153));
        lblNacimiento.setText("Fecha de Nacimiento");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtApellido.setToolTipText("");

        cbxTipoDocu.setBackground(new java.awt.Color(102, 102, 102));
        cbxTipoDocu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxTipoDocu.setForeground(new java.awt.Color(102, 102, 102));
        cbxTipoDocu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Seleccionar)", "CC", "TI", "Pasaporte", "Conduccion", "Carnet" }));

        txtNombre2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtApellido2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtDocumento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyTyped(evt);
            }
        });

        txtPassConfirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emisora/image/desconectar.png"))); // NOI18N
        lblBotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBotonCerrarMouseClicked(evt);
            }
        });

        lblCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(153, 153, 153));
        lblCorreo.setText("Correo");

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblNacimiento))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(jdcCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNombre3)
                                        .addComponent(lblApellido)
                                        .addComponent(lblDocumento)
                                        .addComponent(lblCorreo)
                                        .addComponent(lblPass))
                                    .addGap(50, 50, 50))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1)
                                    .addGap(12, 12, 12)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(32, 32, 32)
                                    .addComponent(lblBotonCerrar))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxTipoDocu, 0, 123, Short.MAX_VALUE)
                                        .addComponent(txtPass, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtDocumento, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtApellido2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(txtCorreo)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBotonCerrar)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblNombre3)
                        .addGap(34, 34, 34)
                        .addComponent(lblApellido)
                        .addGap(31, 31, 31)
                        .addComponent(lblDocumento))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxTipoDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNacimiento)
                        .addGap(18, 18, 18)
                        .addComponent(jdcCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGuardar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //Nos salimos de la app
    private void lblBotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBotonCerrarMouseClicked
        int opcion = JOptionPane.showConfirmDialog(null, "Estás a punto de cerrar la ventana \n  ¿Estás seguro de salir?",
                                                        "Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION){
            dispose();
        }
    }//GEN-LAST:event_lblBotonCerrarMouseClicked

    private void txtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyTyped
        char c=evt.getKeyChar();
        if(Character.isAlphabetic(c)){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese solo valores numéricos.",  "Error de Dato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtDocumentoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(ValidarObligatoriedad()){
        UsuarioEn uen = new UsuarioEn();
        TipoDocumentoEn tdEn = new TipoDocumentoEn();
        int año = jdcCalendar.getCalendar().get(Calendar.YEAR);
        int mes = jdcCalendar.getCalendar().get(Calendar.MARCH);
        int dia = jdcCalendar.getCalendar().get(Calendar.DAY_OF_MONTH);
        
        String fecha = (dia+"/"+mes+"/"+año);
        
        uen.setNombre(txtNombre.getText());
        uen.setNombre2(txtNombre2.getText());
        uen.setApellido(txtApellido.getText());
        uen.setApellido2(txtApellido2.getText());
        tdEn.setTipoDocu(cbxTipoDocu.getItemAt(WIDTH));
        uen.setCorreo(txtCorreo.getText());
        uen.setPass(txtPass.getText());
        uen.setFecha(fecha);
        uen.setDocumento(txtDocumento.getText());      
                
        UsuarioNg ung = new UsuarioNg();
        
        if(ung.guardarUsuario(uen,tdEn)){
                JOptionPane.showMessageDialog(rootPane, "Registro Satisfactorio");            
            }else{
                 JOptionPane.showMessageDialog(rootPane, "Registro no pudo ser guardado");
                }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuario().setVisible(true);
            }
        });
    }
    //Método para validar los campos necesario a actualizar.
    //Este método es una propuesta el cual será modificado posteriormente.
    public boolean ValidarObligatoriedad(){
        boolean validar=true;
        try{                
        if (txtNombre.getText().trim().length()==0){ 
            validar=false;
            JOptionPane.showMessageDialog(rootPane, "Por lo menos proporcina 1 nombre.",  "Error de Dato", JOptionPane.ERROR_MESSAGE);
        }
        if (txtApellido.getText().trim().length()==0){ 
            validar=false;
            JOptionPane.showMessageDialog(rootPane, "Por lo menos proporciona 1 apellido.",  "Error de Dato", JOptionPane.ERROR_MESSAGE);
        }
        if (cbxTipoDocu.getSelectedItem().toString().equals("(Seleccionar)")){ 
            validar=false;
            JOptionPane.showMessageDialog(rootPane, "El tipo de documento es dato obligatorio.",  "Error de Dato", JOptionPane.ERROR_MESSAGE);
        }
        if (txtDocumento.getText().trim().length()==0){ 
            validar=false;
            JOptionPane.showMessageDialog(rootPane, "El Documento es dato obligatorio.",  "Error de Dato", JOptionPane.ERROR_MESSAGE);
        }
        if (Double.parseDouble(txtDocumento.getText())<1){
            validar=false;
            JOptionPane.showMessageDialog(rootPane, "El documento no puede ser 0.",  "Error de Dato", JOptionPane.ERROR_MESSAGE);
        }
        if (txtDocumento.getText().trim().length()>=10){ 
            validar=false;
            JOptionPane.showMessageDialog(rootPane, "El Documento no puede exceder los 10 digitos.",  "Error de Dato", JOptionPane.ERROR_MESSAGE);
        }
        if (txtPass.getText().trim().length()==0){ 
            validar=false;
            JOptionPane.showMessageDialog(rootPane, "La contraseña es un campo obligatorio.",  "Error de Dato", JOptionPane.ERROR_MESSAGE);
        }       
        if (!txtPass.getText().equals(txtPassConfirm.getText())){
            validar=false;
            JOptionPane.showMessageDialog(rootPane, "Las contraseñasdeben coincidir.",  "Error de Dato", JOptionPane.ERROR_MESSAGE);
        }
        if (txtCorreo.getText().trim().length()==0){
            validar=false;
            JOptionPane.showMessageDialog(rootPane, "El correo es un campo necesario.",  "Error de Dato", JOptionPane.ERROR_MESSAGE);
        }
        if (jdcCalendar.getCalendar()==null){
            validar=false;
            JOptionPane.showMessageDialog(rootPane, "Debe proporcionarse una fecha.",  "Error de Dato", JOptionPane.ERROR_MESSAGE);            
        }
        
        }catch(Exception ex){
        }
        return validar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxTipoDocu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jdcCalendar;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblBotonCerrar;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblNacimiento;
    private javax.swing.JLabel lblNombre3;
    private javax.swing.JLabel lblPass;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPassConfirm;
    // End of variables declaration//GEN-END:variables
}
